Repository enflujo/arca-www, pull requests merged in 2023-02, with the labels that each got.

#94 🎨 Estandarizar variables SCSS y CSS
  __BACKUP/components/DescripcionGaleria.vue
  __BACKUP/components/EtiquetasGaleria.vue
  __BACKUP/components/Filtros.vue
  __BACKUP/components/MapaDashboard.vue
  __BACKUP/components/MapaUno.vue
  __BACKUP/components/Paginas.vue
  __BACKUP/components/Vue-magnifier.vue
  __BACKUP/pages/imagen/[id].vue
  __BACKUP/pages/mapa/[pais].vue
  __BACKUP/pages/sobre-arca/index.vue
  __BACKUP/pages/visualizacion-datos/index.vue
  assets/scss/_constantes.scss
  assets/scss/_general.scss
  assets/scss/_normalizar.scss
  components/Buscador.vue
  components/Cargador.vue
  components/Galeria/Mosaico.vue
  components/Guardaescobas.vue
  components/Menu/Buscador.vue
  components/Menu/General.vue
  components/Menu/Vistas.vue
  layouts/conBuscador.vue
  layouts/default.vue
  pages/archivo/obras/[registro].vue
  pages/archivo/ubicaciones/index.vue
  pages/index.vue
Labels: mejora :ant:, optimización :zap:

#98 Categorias y colombinas
  __BACKUP/components/DescripcionGaleria.vue
  __BACKUP/components/EtiquetasGaleria.vue
  __BACKUP/components/Filtros.vue
  __BACKUP/components/MapaDashboard.vue
  __BACKUP/components/MapaUno.vue
  __BACKUP/components/Paginas.vue
  __BACKUP/components/Vue-magnifier.vue
  __BACKUP/pages/imagen/[id].vue
  __BACKUP/pages/mapa/[pais].vue
  __BACKUP/pages/sobre-arca/index.vue
  __BACKUP/pages/visualizacion-datos/index.vue
  assets/imgs/boton_alfabetico.svg
  assets/imgs/boton_colombinas.svg
  assets/imgs/boton_geo.svg
  assets/scss/_constantes.scss
  assets/scss/_general.scss
  assets/scss/_normalizar.scss
  cerebros/archivo.js
  components/Buscador.vue
  components/Cargador.vue
  components/Galeria/Mosaico.vue
  components/Galeria/index.vue
  components/Grafica/Arbol.vue
  components/Guardaescobas.vue
  components/Menu/Buscador.vue
  components/Menu/General.vue
  components/Menu/Paginas.vue
  components/Menu/Vistas.vue
  composables/obtenerDatos.ts
  layouts/conBuscador.vue
  layouts/default.vue
  package.json
  pages/archivo/autores/[id].vue
  pages/archivo/autores/index.vue
  pages/archivo/categorias[[numero]]/[id].vue
  pages/archivo/categorias[[numero]]/index.vue
  pages/archivo/obras/[registro].vue
  pages/archivo/ubicaciones/[id].vue
  pages/archivo/ubicaciones/index.vue
  pages/index.vue
  utilidades/ayudas.js
  utilidades/queries.js
  yarn.lock
Labels: front-end :art:, ui :ocean:

#106 🧵 Enlaces directos a las vistas, resuelve #96
  pages/archivo/ubicaciones/index.vue
Labels: bicho :bug:

#113 🐛 Ajustes pantallas gigantes
  assets/scss/_constantes.scss
  components/Guardaescobas.vue
  components/Menu/Buscador.vue
  components/Menu/General.vue
  layouts/conBuscador.vue
  layouts/default.vue
Labels: bicho :bug:, front-end :art:

#114 Grilla en gráfica colombinas 🍭
  components/Filtros.vue
  components/Grafica/Colombinas.vue
  pages/archivo/ubicaciones/index.vue
Labels: front-end :art:, ui :ocean:

#117 💄 cambiar color de cantidad de obras en colombinas
  components/Galeria/Mosaico.vue
  components/Grafica/Colombinas.vue
Labels: front-end :art:
